name: Test & Lint App

on:
  workflow_call:
    inputs:
      node-version:
        type: number
        description: 'Node version to be used'
        required: true
      repository:
        type: string
        description: 'Repository that is using the workflow'
        required: true
      checkout-ref:
        type: string
        description: 'Branch that will run the workflow'
        required: true
      cache-key:
        type: string
        description: 'Cache key to be used'
        required: true

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo repo: "${{ inputs.repository }}"
          echo ref: "${{ inputs.checkout-ref }}"
          echo node: "${{ inputs.node-version }}"
          echo cache: "${{ inputs.cache-key }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Load or Install Dependencies
        uses: hubarthurcoelho/my-workflows/.github/actions/cache-deps@main
        with:
          node-version: ${{ inputs.node-version }}
          cache-key: ${{ inputs.cache-key }}

      - name: Run Tests
        run: npm test

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Load or Install Dependencies
        uses: hubarthurcoelho/my-workflows/.github/actions/cache-deps@main
        with:
          node-version: ${{ inputs.node-version }}
          cache-key: ${{ inputs.cache-key }}
  
      - name: Run Lint
        run: npm test
